export const permissionOptions = {
  Dashboard: [{ label: "View", value: "view" }],
  Product_Management: [
    { label: "Add", value: "add" },
    { label: "Update", value: "update" },
    { label: "Delete", value: "delete" },
    { label: "View", value: "view" },
    // { label: "enable", value: "enable" },
  ],
  Product_Sub_Category_Management: [
    { label: "Add", value: "add" },
    { label: "Update", value: "update" },
    { label: "Delete", value: "delete" },
    { label: "View", value: "view" },
    // { label: "enable", value: "enable" },
  ],
  User_Management: [
    { label: "Add", value: "add" },
    { label: "Update", value: "update" },
    { label: "Delete", value: "delete" },
    { label: "View", value: "view" },
    // { label: "enable", value: "enable" },
  ],
  Promotions_and_Discounts: [
    { label: "Add", value: "add" },
    { label: "Update", value: "update" },
    { label: "Delete", value: "delete" },
    { label: "View", value: "view" },
    // { label: "enable", value: "enable" },
  ],
  Return_and_Refund_Management: [
    { label: "Add", value: "add" },
    { label: "Update", value: "update" },
    { label: "Delete", value: "delete" },
    { label: "View", value: "view" },
    // { label: "enable", value: "enable" },
  ],
  Product_Category_Management: [
    { label: "Add", value: "add" },
    { label: "Update", value: "update" },
    { label: "Delete", value: "delete" },
    { label: "View", value: "view" },
    // { label: "enable", value: "enable" },
  ],
  Permissions_and_Roles: [
    { label: "Add", value: "add" },
    { label: "Update", value: "update" },
    { label: "Delete", value: "delete" },
    { label: "View", value: "view" },
    // { label: "enable", value: "enable" },
  ],
  Analytics_and_Reporting: [
    { label: "Add", value: "add" },
    { label: "Update", value: "update" },
    { label: "Delete", value: "delete" },
    { label: "View", value: "view" },
    // { label: "enable", value: "enable" },
  ],
  Customer_Support: [
    { label: "Add", value: "add" },
    { label: "Update", value: "update" },
    { label: "Delete", value: "delete" },
    { label: "View", value: "view" },
    // { label: "enable", value: "enable" },
  ],
  Shipping_Management: [
    { label: "Add", value: "add" },
    { label: "Update", value: "update" },
    { label: "Delete", value: "delete" },
    { label: "View", value: "view" },
    // { label: "enable", value: "enable" },
  ],
  Content_Management: [
    { label: "Add", value: "add" },
    { label: "Update", value: "update" },
    { label: "Delete", value: "delete" },
    { label: "View", value: "view" },
    // { label: "enable", value: "enable" },
  ],
  Dashboard_Customization: [
    { label: "Add", value: "add" },
    { label: "Update", value: "update" },
    { label: "Delete", value: "delete" },
    { label: "View", value: "view" },
    // { label: "enable", value: "enable" },
  ],
  Multi_language_Support: [
    { label: "Add", value: "add" },
    { label: "Update", value: "update" },
    { label: "Delete", value: "delete" },
    { label: "View", value: "view" },
    // { label: "enable", value: "enable" },
  ],
  Backup_and_Recovery: [
    { label: "Add", value: "add" },
    { label: "Update", value: "update" },
    { label: "Delete", value: "delete" },
    { label: "View", value: "view" },
    // { label: "enable", value: "enable" },
  ],
  Notification_Management: [
    { label: "Add", value: "add" },
    { label: "Update", value: "update" },
    { label: "Delete", value: "delete" },
    { label: "View", value: "view" },
    // { label: "enable", value: "enable" },
  ],
  Tax_Management: [
    { label: "Add", value: "add" },
    { label: "Update", value: "update" },
    { label: "Delete", value: "delete" },
    { label: "View", value: "view" },
    // { label: "enable", value: "enable" },
  ],
  Order_Management: [
    { label: "Add", value: "add" },
    { label: "Update", value: "update" },
    { label: "Delete", value: "delete" },
    { label: "View", value: "view" },
    // { label: "enable", value: "enable" },
  ],
};

export const getActualRole = {
  Dashboard: "Dashboard",
  Product_Category_Management: "Product Category Management",
  Product_management: "Product Management",
  Product_Sub_Category_Management: "Product Sub Category Management",
  User_Management: "User Management",
  Promotions_and_Discounts: "Promotions and Discounts",
  Return_and_Refund_Management: "Return and Refund Management",
  Permissions_and_Roles: "Permissions and Roles",
  Analytics_and_Reporting: "Analytics and Reporting",
  Customer_Support: "Customer Support",
  Shipping_Management: "Shipping Management",
  Order_Management: "Order Management",
  Tax_Management: "Tax Management",
  Notification_Management: "Notification Management",
  Backup_and_Recovery: "Backup and Recovery",
  Multi_language_Support: "Multi language Support",
  Dashboard_Customization: "Dashboard Customization",
};
