export const permissionOptions = {
  Dashboard: [{ label: 'View', value: 'view' }],
  Product_Management: [
    { label: 'Add', value: 'add' },
    { label: 'Update', value: 'update' },
    { label: 'Delete', value: 'delete' },
    { label: 'View', value: 'view' },
    // { label: "enable", value: "enable" },
  ],
  Product_Sub_Category_Management: [
    { label: 'Add', value: 'add' },
    { label: 'Update', value: 'update' },
    { label: 'Delete', value: 'delete' },
    { label: 'View', value: 'view' },
    // { label: "enable", value: "enable" },
  ],
  Product_Author_Management: [
    { label: 'Add', value: 'add' },
    { label: 'Update', value: 'update' },
    { label: 'Delete', value: 'delete' },
    { label: 'View', value: 'view' },
    // { label: "enable", value: "enable" },
  ],
  Product_Category_Management: [
    { label: 'Add', value: 'add' },
    { label: 'Update', value: 'update' },
    { label: 'Delete', value: 'delete' },
    { label: 'View', value: 'view' },
    // { label: "enable", value: "enable" },
  ],
  Product_Coupon_Management: [
    { label: 'Add', value: 'add' },
    { label: 'Update', value: 'update' },
    { label: 'Delete', value: 'delete' },
    { label: 'View', value: 'view' },
  ],
  User_Management: [
    { label: 'Add', value: 'add' },
    { label: 'Update', value: 'update' },
    { label: 'Delete', value: 'delete' },
    { label: 'View', value: 'view' },
    // { label: "enable", value: "enable" },
  ],
  Order_User_Management: [
    { label: 'Add', value: 'add' },
    { label: 'Update', value: 'update' },
    { label: 'Delete', value: 'delete' },
    { label: 'View', value: 'view' },
    // { label: "enable", value: "enable" },
  ],

  Assign_Order_Management: [
    { label: 'Add', value: 'add' },
    { label: 'Update', value: 'update' },
    { label: 'Delete', value: 'delete' },
    { label: 'View', value: 'view' },
    // { label: "enable", value: "enable" },
  ],
  Permissions_and_Roles: [
    { label: 'Add', value: 'add' },
    { label: 'Update', value: 'update' },
    { label: 'Delete', value: 'delete' },
    { label: 'View', value: 'view' },
    // { label: "enable", value: "enable" },
  ],
  Home_Management: [
    { label: 'Add', value: 'add' },
    { label: 'Update', value: 'update' },
    { label: 'Delete', value: 'delete' },
    { label: 'View', value: 'view' },
    // { label: "enable", value: "enable" },
  ],
  Customer_Support: [
    { label: 'Add', value: 'add' },
    { label: 'Update', value: 'update' },
    { label: 'Delete', value: 'delete' },
    { label: 'View', value: 'view' },
    // { label: "enable", value: "enable" },
  ],
  Shipping_Management: [
    { label: 'Add', value: 'add' },
    { label: 'Update', value: 'update' },
    { label: 'Delete', value: 'delete' },
    { label: 'View', value: 'view' },
    // { label: "enable", value: "enable" },
  ],
  Content_Management: [
    { label: 'Add', value: 'add' },
    { label: 'Update', value: 'update' },
    { label: 'Delete', value: 'delete' },
    { label: 'View', value: 'view' },
    // { label: "enable", value: "enable" },
  ],
  Dashboard_Customization: [
    { label: 'Add', value: 'add' },
    { label: 'Update', value: 'update' },
    { label: 'Delete', value: 'delete' },
    { label: 'View', value: 'view' },
    // { label: "enable", value: "enable" },
  ],
  Multi_language_Support: [
    { label: 'Add', value: 'add' },
    { label: 'Update', value: 'update' },
    { label: 'Delete', value: 'delete' },
    { label: 'View', value: 'view' },
    // { label: "enable", value: "enable" },
  ],
  Backup_and_Recovery: [
    { label: 'Add', value: 'add' },
    { label: 'Update', value: 'update' },
    { label: 'Delete', value: 'delete' },
    { label: 'View', value: 'view' },
    // { label: "enable", value: "enable" },
  ],
  Notification_Management: [
    { label: 'Add', value: 'add' },
    { label: 'Update', value: 'update' },
    { label: 'Delete', value: 'delete' },
    { label: 'View', value: 'view' },
    // { label: "enable", value: "enable" },
  ],
  Tax_Management: [
    { label: 'Add', value: 'add' },
    { label: 'Update', value: 'update' },
    { label: 'Delete', value: 'delete' },
    { label: 'View', value: 'view' },
    // { label: "enable", value: "enable" },
  ],
  Order_Management: [
    { label: 'Add', value: 'add' },
    { label: 'Update', value: 'update' },
    { label: 'Delete', value: 'delete' },
    { label: 'View', value: 'view' },
    // { label: "enable", value: "enable" },
  ],
}

export const getActualRole = {
  Dashboard: 'Dashboard',
  Product_Category_Management: 'Product Category Management',
  Product_Management: 'Product Management',
  Product_Sub_Category_Management: 'Product Sub Category Management',
  User_Management: 'User Management',
  Promotions_and_Discounts: 'Promotions and Discounts',
  Return_and_Refund_Management: 'Return and Refund Management',
  Permissions_and_Roles: 'Permissions and Roles',
  Analytics_and_Reporting: 'Analytics and Reporting',
  Customer_Support: 'Customer Support',
  Shipping_Management: 'Shipping Management',
  Order_Management: 'Order Management',
  Tax_Management: 'Tax Management',
  Notification_Management: 'Notification Management',
  Backup_and_Recovery: 'Backup and Recovery',
  Multi_language_Support: 'Multi language Support',
  Dashboard_Customization: 'Dashboard Customization',
}

export const roleOptions = [
  'Dashboard',
  'Product_Category_Management',
  'Product_Management',
  'Product_Sub_Category_Management',
  'User_Management',
  'Promotions_and_Discounts',
  'Return_and_Refund_Management',
  'Permissions_and_Roles',
  'Analytics_and_Reporting',
  'Customer_Support',
  'Shipping_Management',
  'Order_Management',
  'Tax_Management',
  'Notification_Management',
  'Backup_and_Recovery',
  'Multi_language_Support',
  'Dashboard_Customization',
]
