name: Netlify Deploy (Staging)

on:
  push:
    branches:
      - staging # Change this to your staging branch

jobs:
  build:
    name: Run Application Job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install dependencies
        run: yarn install --save-exact

      - name: Build
        run: yarn run build

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2.3
        with:
          publish-dir: "./dist"
          production-branch: staging
          deploy-message: "${{ github.event.head_commit.message }}"
        env:
          NETLIFY_SITE_ID: "${{ secrets.NETLIFY_STAGING_SITE_ID }}"
          NETLIFY_AUTH_TOKEN: "${{ secrets.NETLIFY_AUTH_TOKEN }}"

      - name: Pull environment variables from Netlify
        run: |
          curl -X GET -H "Authorization: Bearer $NETLIFY_AUTH_TOKEN" https://api.netlify.com/api/v1/sites/$NETLIFY_SITE_ID
